services:
  - type: worker
    name: BIBOZX3_LIVE_BOT
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: COINGLASS_API_KEY
        sync: false